package org.scalajs.jquery

import scala.scalajs.js
import org.scalajs.dom._

trait JQueryAjaxSettings extends js.Object {
  var accepts: js.Any = _
  var async: js.Boolean = _
  def beforeSend(jqXHR: JQueryXHR, settings: JQueryAjaxSettings): js.Dynamic = ???
  var cache: js.Boolean = _
  def complete(jqXHR: JQueryXHR, textStatus: js.String): js.Dynamic = ???
  var contents: js.Any = _
  var contentType: js.Any = _
  var context: js.Any = _
  var converters: js.Any = _
  var crossDomain: js.Boolean = _
  var data: js.Any = _
  def dataFilter(data: js.Any, ty: js.Any): js.Dynamic = ???
  var dataType: js.String = _
  def error(jqXHR: JQueryXHR, textStatus: js.String, errorThrow: js.String): js.Dynamic = ???
  var global: js.Boolean = _
  var headers: js.Any = _
  var ifModified: js.Boolean = _
  var isLocal: js.Boolean = _
  var jsonp: js.String = _
  var jsonpCallback: js.Any = _
  var mimeType: js.String = _
  var password: js.String = _
  var processData: js.Boolean = _
  var scriptCharset: js.String = _
  var statusCode: js.Any = _
  def success(data: js.Any, textStatus: js.String, jqXHR: JQueryXHR): js.Dynamic = ???
  var timeout: js.Number = _
  var traditional: js.Boolean = _
  var `type`: js.String = _
  var url: js.String = _
  var username: js.String = _
  var xhr: js.Any = _
  var xhrFields: js.Any = _
}

trait JQueryXHR extends XMLHttpRequest {
  def overrideMimeType(): js.Dynamic = ???
}

trait JQueryCallback extends js.Object {
  def add(callbacks: js.Any*): js.Dynamic = ???
  def disable(): js.Dynamic = ???
  def empty(): js.Dynamic = ???
  def fire(arguments: js.Any*): js.Dynamic = ???
  def fired(): js.Boolean = ???
  def fireWith(context: js.Any, args: js.Any*): js.Dynamic = ???
  def has(callback: js.Any): js.Boolean = ???
  def lock(): js.Dynamic = ???
  def locked(): js.Boolean = ???
  def removed(callbacks: js.Any*): js.Dynamic = ???
}

trait JQueryPromise extends js.Object {
  def always(alwaysCallbacks: js.Any*): JQueryDeferred = ???
  def done(doneCallbacks: js.Any*): JQueryDeferred = ???
  def fail(failCallbacks: js.Any*): JQueryDeferred = ???
  def pipe(doneFilter: js.Function1[js.Any, js.Any], failFilter: js.Function1[js.Any, js.Any], progressFilter: js.Function1[js.Any, js.Any]): JQueryPromise = ???
  def pipe(doneFilter: js.Function1[js.Any, js.Any], failFilter: js.Function1[js.Any, js.Any]): JQueryPromise = ???
  def pipe(doneFilter: js.Function1[js.Any, js.Any]): JQueryPromise = ???
  def pipe(): JQueryPromise = ???
  def `then`(doneCallbacks: js.Any, failCallbacks: js.Any, progressCallbacks: js.Any): JQueryDeferred = ???
  def `then`(doneCallbacks: js.Any, failCallbacks: js.Any): JQueryDeferred = ???
}

trait JQueryDeferred extends JQueryPromise {
  def notify(args: js.Any*): JQueryDeferred = ???
  def notifyWith(context: js.Any, args: js.Any*): JQueryDeferred = ???
  def progress(progressCallbacks: js.Any*): JQueryDeferred = ???
  def reject(args: js.Any*): JQueryDeferred = ???
  def rejectWith(context: js.Any, args: js.Any*): JQueryDeferred = ???
  def resolve(args: js.Any*): JQueryDeferred = ???
  def resolveWith(context: js.Any, args: js.Any*): JQueryDeferred = ???
  def state(): js.String = ???
  override def `then`(doneCallbacks: js.Any, failCallbacks: js.Any, progressCallbacks: js.Any): JQueryDeferred = ???
  override def `then`(doneCallbacks: js.Any, failCallbacks: js.Any): JQueryDeferred = ???
  def `then`(doneCallbacks: js.Any): JQueryDeferred = ???
}

trait JQueryEventObject extends Event {
  var data: js.Any = _
  var delegateTarget: Element = _
  def isDefaultPrevented(): js.Boolean = ???
  def isImmediatePropogationStopped(): js.Boolean = ???
  def isPropogationStopped(): js.Boolean = ???
  var namespace: js.String = _
  override def preventDefault(): Unit = ??? // js.Dynamic
  var relatedTarget: Element = _
  var result: js.Any = _
  override def stopImmediatePropagation(): Unit = ??? // js.Dynamic
  override def stopPropagation(): Unit = ??? // js.Dynamic
  var pageX: js.Number = _
  var pageY: js.Number = _
  var which: js.Number = _
  var metaKey: js.Any = _
}

trait JQueryBrowserInfo extends js.Object {
  var safari: js.Boolean = _
  var opera: js.Boolean = _
  var msie: js.Boolean = _
  var mozilla: js.Boolean = _
  var version: js.String = _
}

trait JQuerySupport extends js.Object {
  var ajax: js.Boolean = _
  var boxModel: js.Boolean = _
  var changeBubbles: js.Boolean = _
  var checkClone: js.Boolean = _
  var checkOn: js.Boolean = _
  var cors: js.Boolean = _
  var cssFloat: js.Boolean = _
  var hrefNormalized: js.Boolean = _
  var htmlSerialize: js.Boolean = _
  var leadingWhitespace: js.Boolean = _
  var noCloneChecked: js.Boolean = _
  var noCloneEvent: js.Boolean = _
  var opacity: js.Boolean = _
  var optDisabled: js.Boolean = _
  var optSelected: js.Boolean = _
  def scriptEval(): js.Boolean = ???
  var style: js.Boolean = _
  var submitBubbles: js.Boolean = _
  var tbody: js.Boolean = _
}

trait JQueryTransport extends js.Object {
  def send(headers: js.Any, completeCallback: js.Function4[js.Number, js.String, js.Any, js.String, Unit]): Unit = ???
  def abort(): Unit = ???
}

trait JQueryStatic extends js.Object {
  def ajax(settings: JQueryAjaxSettings): js.Dynamic = ???
  def ajax(url: js.String, settings: JQueryAjaxSettings): js.Dynamic = ???
  def ajaxPrefilter(dataTypes: js.String, handler: js.Function3[js.Any, js.Any, JQueryXHR, js.Any]): js.Dynamic = ???
  def ajaxPrefilter(handler: js.Function3[js.Any, js.Any, JQueryXHR, js.Any]): js.Dynamic = ???
  def ajaxSetup(options: js.Any): js.Dynamic = ???
  def ajaxTransport(dataType: js.String, handler: js.Function3[JQueryAjaxSettings, JQueryAjaxSettings, JQueryXHR, JQueryTransport]): Unit = ???
  def get(url: js.String, data: js.Any, success: js.Any, dataType: js.Any): JQueryXHR = ???
  def get(url: js.String, data: js.Any, success: js.Any): JQueryXHR = ???
  def get(url: js.String, data: js.Any): JQueryXHR = ???
  def get(url: js.String): JQueryXHR = ???
  def getJSON(url: js.String, data: js.Any, success: js.Any): JQueryXHR = ???
  def getJSON(url: js.String, data: js.Any): JQueryXHR = ???
  def getJSON(url: js.String): JQueryXHR = ???
  def getScript(url: js.String, success: js.Any): JQueryXHR = ???
  def getScript(url: js.String): JQueryXHR = ???
  def param(obj: js.Any): js.String = ???
  def param(obj: js.Any, traditional: js.Boolean): js.String = ???
  def post(url: js.String, data: js.Any, success: js.Any, dataType: js.Any): JQueryXHR = ???
  def post(url: js.String, data: js.Any, success: js.Any): JQueryXHR = ???
  def post(url: js.String, data: js.Any): JQueryXHR = ???
  def post(url: js.String): JQueryXHR = ???
  def Callbacks(flags: js.Any): JQueryCallback = ???
  def holdReady(hold: js.Boolean): js.Dynamic = ???
  def apply(selector: js.String, context: js.Any): JQuery = ???
  def apply(selector: js.String): JQuery = ???
  def apply(element: Element): JQuery = ???
  def apply(`object`: js.Any): JQuery = ???
  def apply(elementArray: js.Array[Element]): JQuery = ???
  def apply(`object`: JQuery): JQuery = ???
  def apply(func: js.Function): JQuery = ???
  def apply(): JQuery = ???
  def noConflict(removeAll: js.Boolean): Object = ???
  def noConflict(): Object = ???
  def when(deferreds: js.Any*): JQueryPromise = ???
  def css(e: js.Any, propertyName: js.String, value: js.Any): js.Dynamic = ???
  def css(e: js.Any, propertyName: js.String): js.Dynamic = ???
  def css(e: js.Any, propertyName: js.Any, value: js.Any): js.Dynamic = ???
  def css(e: js.Any, propertyName: js.Any): js.Dynamic = ???
  var cssHooks: js.Any = _
  def data(element: Element, key: js.String, value: js.Any): Object = ???
  def dequeue(element: Element, queueName: js.String): js.Dynamic = ???
  def dequeue(element: Element): js.Dynamic = ???
  def hasData(element: Element): js.Boolean = ???
  def queue(element: Element, queueName: js.String): js.Array[js.Any] = ???
  def queue(element: Element): js.Array[js.Any] = ???
  def queue(element: Element, queueName: js.String, newQueueOrCallback: js.Any): JQuery = ???
  def removeData(element: Element, name: js.String): JQuery = ???
  def removeData(element: Element): JQuery = ???
  def Deferred(beforeStart: js.Function1[JQueryDeferred, js.Any]): JQueryDeferred = ???
  def Deferred(): JQueryDeferred = ???
  var fx: js.Any = _
  def proxy(func: js.Function, context: js.Any): js.Dynamic = ???
  def proxy(context: js.Any, name: js.String): js.Dynamic = ???
  def error(message: js.Any): js.Dynamic = ???
  var expr: js.Any = _
  var fn: js.Any = _
  var isReady: js.Boolean = _
  var browser: JQueryBrowserInfo = _
  var support: JQuerySupport = _
  def contains(container: Element, contained: Element): js.Boolean = ???
  def each(collection: js.Any, callback: js.Function2[js.Any, js.Any, js.Any]): js.Dynamic = ???
  def extend(target: js.Any, objs: js.Any*): Object = ???
  def extend(deep: js.Boolean, target: js.Any, objs: js.Any*): Object = ???
  def globalEval(code: js.String): js.Dynamic = ???
  def grep(array: js.Array[js.Any], func: js.Any, invert: js.Boolean): js.Array[js.Any] = ???
  def inArray(value: js.Any, array: js.Array[js.Any], fromIndex: js.Number): js.Number = ???
  def inArray(value: js.Any, array: js.Array[js.Any]): js.Number = ???
  def isArray(obj: js.Any): js.Boolean = ???
  def isEmptyObject(obj: js.Any): js.Boolean = ???
  def isFunction(obj: js.Any): js.Boolean = ???
  def isNumeric(value: js.Any): js.Boolean = ???
  def isPlainObject(obj: js.Any): js.Boolean = ???
  def isWindow(obj: js.Any): js.Boolean = ???
  def isXMLDoc(node: Node): js.Boolean = ???
  def makeArray(obj: js.Any): js.Array[js.Any] = ???
  def map(array: js.Array[js.Any], callback: js.Function2[js.Any, js.Any, js.Any]): js.Array[js.Any] = ???
  def merge(first: js.Array[js.Any], second: js.Array[js.Any]): js.Array[js.Any] = ???
  def noop(): js.Dynamic = ???
  def now(): js.Number = ???
  def parseHTML(data: js.String, context: Element, keepScripts: js.Boolean): js.Array[js.Any] = ???
  def parseHTML(data: js.String, context: Element): js.Array[js.Any] = ???
  def parseHTML(data: js.String): js.Array[js.Any] = ???
  def parseJSON(json: js.String): js.Dynamic = ???
  def parseXML(data: js.String): js.Dynamic = ???
  def queue(element: Element, queueName: js.String, newQueue: js.Array[js.Any]): JQuery = ???
  def trim(str: js.String): js.String = ???
  def `type`(obj: js.Any): js.String = ???
  def unique(arr: js.Array[js.Any]): js.Array[js.Any] = ???
}

trait JQuery extends js.Object {
  def ajaxComplete(handler: js.Any): JQuery = ???
  def ajaxError(handler: js.Function3[js.Any, js.Any, js.Any, js.Any]): JQuery = ???
  def ajaxSend(handler: js.Function3[js.Any, js.Any, js.Any, js.Any]): JQuery = ???
  def ajaxStart(handler: js.Function0[js.Any]): JQuery = ???
  def ajaxStop(handler: js.Function0[js.Any]): JQuery = ???
  def ajaxSuccess(handler: js.Function3[js.Any, js.Any, js.Any, js.Any]): JQuery = ???
  def serialize(): js.String = ???
  def serializeArray(): js.Array[js.Any] = ???
  def addClass(classNames: js.String): JQuery = ???
  def addClass(func: js.Function2[js.Any, js.Any, JQuery]): js.Dynamic = ???
  def attr(attributeName: js.String): js.String = ???
  def attr(attributeName: js.String, value: js.Any): JQuery = ???
  def attr(map: js.Any): JQuery = ???
  def attr(attributeName: js.String, func: js.Function2[js.Any, js.Any, js.Any]): JQuery = ???
  def hasClass(className: js.String): js.Boolean = ???
  def html(htmlString: js.String): JQuery = ???
  def html(): js.String = ???
  def prop(propertyName: js.String): js.Dynamic = ???
  def prop(propertyName: js.String, value: js.Any): JQuery = ???
  def prop(map: js.Any): JQuery = ???
  def prop(propertyName: js.String, func: js.Function2[js.Any, js.Any, js.Any]): JQuery = ???
  def removeAttr(attributeName: js.Any): JQuery = ???
  def removeClass(className: js.Any): JQuery = ???
  def removeClass(): JQuery = ???
  def removeClass(func: js.Function2[js.Any, js.Any, js.Any]): JQuery = ???
  def removeProp(propertyName: js.Any): JQuery = ???
  def toggleClass(className: js.Any, swtch: js.Boolean): JQuery = ???
  def toggleClass(className: js.Any): JQuery = ???
  def toggleClass(swtch: js.Boolean): JQuery = ???
  def toggleClass(): JQuery = ???
  def toggleClass(func: js.Function3[js.Any, js.Any, js.Any, js.Any]): JQuery = ???
  def `val`(): js.Dynamic = ???
  def `val`(value: js.Array[js.String]): JQuery = ???
  def `val`(value: js.String): JQuery = ???
  def `val`(func: js.Function2[js.Any, js.Any, js.Any]): JQuery = ???
  def css(propertyNames: js.Array[js.Any]): js.String = ???
  def css(propertyName: js.String): js.String = ???
  def css(propertyName: js.String, value: js.Any): JQuery = ???
  def css(propertyName: js.Any, value: js.Any): JQuery = ???
  def css(propertyName: js.Any): JQuery = ???
  def height(): js.Number = ???
  def height(value: js.Number): JQuery = ???
  def height(func: js.Function2[js.Any, js.Any, js.Any]): JQuery = ???
  def innerHeight(): js.Number = ???
  def innerWidth(): js.Number = ???
  def offset(): js.Any = ???
  def offset(coordinates: js.Any): JQuery = ???
  def offset(func: js.Function2[js.Any, js.Any, js.Any]): JQuery = ???
  def outerHeight(includeMargin: js.Boolean): js.Number = ???
  def outerHeight(): js.Number = ???
  def outerWidth(includeMargin: js.Boolean): js.Number = ???
  def outerWidth(): js.Number = ???
  def position(): js.Any = ???
  def scrollLeft(): js.Number = ???
  def scrollLeft(value: js.Number): JQuery = ???
  def scrollTop(): js.Number = ???
  def scrollTop(value: js.Number): JQuery = ???
  def width(): js.Number = ???
  def width(value: js.Number): JQuery = ???
  def width(func: js.Function2[js.Any, js.Any, js.Any]): JQuery = ???
  def clearQueue(queueName: js.String): JQuery = ???
  def clearQueue(): JQuery = ???
  def data(key: js.String, value: js.Any): JQuery = ???
  def data(obj: js.Any): JQuery = ???
  def data(key: js.String): js.Dynamic = ???
  def data(): js.Dynamic = ???
  def dequeue(queueName: js.String): JQuery = ???
  def dequeue(): JQuery = ???
  def queue(queueName: js.String): js.Array[js.Any] = ???
  def queue(): js.Array[js.Any] = ???
  def queue(queueName: js.String, newQueueOrCallback: js.Any): JQuery = ???
  def queue(newQueueOrCallback: js.Any): JQuery = ???
  def removeData(nameOrList: js.Any): JQuery = ???
  def removeData(): JQuery = ???
  def promise(`type`: js.Any, target: js.Any): JQueryPromise = ???
  def promise(`type`: js.Any): JQueryPromise = ???
  def promise(): JQueryPromise = ???
  def animate(properties: js.Any, duration: js.Any, easing: js.String, complete: js.Function): JQuery = ???
  def animate(properties: js.Any, duration: js.Any, easing: js.String): JQuery = ???
  def animate(properties: js.Any, duration: js.Any): JQuery = ???
  def animate(properties: js.Any): JQuery = ???
  def delay(duration: js.Number, queueName: js.String): JQuery = ???
  def delay(duration: js.Number): JQuery = ???
  def fadeIn(duration: js.Any, callback: js.Any): JQuery = ???
  def fadeIn(duration: js.Any): JQuery = ???
  def fadeIn(): JQuery = ???
  def fadeIn(duration: js.Any, easing: js.String, callback: js.Any): JQuery = ???
  def fadeIn(duration: js.Any, easing: js.String): JQuery = ???
  def fadeOut(duration: js.Any, callback: js.Any): JQuery = ???
  def fadeOut(duration: js.Any): JQuery = ???
  def fadeOut(): JQuery = ???
  def fadeOut(duration: js.Any, easing: js.String, callback: js.Any): JQuery = ???
  def fadeOut(duration: js.Any, easing: js.String): JQuery = ???
  def fadeTo(duration: js.Any, opacity: js.Number, callback: js.Any): JQuery = ???
  def fadeTo(duration: js.Any, opacity: js.Number): JQuery = ???
  def fadeTo(duration: js.Any, opacity: js.Number, easing: js.String, callback: js.Any): JQuery = ???
  def fadeTo(duration: js.Any, opacity: js.Number, easing: js.String): JQuery = ???
  def fadeToggle(duration: js.Any, easing: js.String, callback: js.Any): JQuery = ???
  def fadeToggle(duration: js.Any, easing: js.String): JQuery = ???
  def fadeToggle(duration: js.Any): JQuery = ???
  def fadeToggle(): JQuery = ???
  def finish(queue: js.String): JQuery = ???
  def finish(): JQuery = ???
  def hide(duration: js.Any, callback: js.Any): JQuery = ???
  def hide(duration: js.Any): JQuery = ???
  def hide(): JQuery = ???
  def hide(duration: js.Any, easing: js.String, callback: js.Any): JQuery = ???
  def hide(duration: js.Any, easing: js.String): JQuery = ???
  def show(duration: js.Any, callback: js.Any): JQuery = ???
  def show(duration: js.Any): JQuery = ???
  def show(): JQuery = ???
  def show(duration: js.Any, easing: js.String, callback: js.Any): JQuery = ???
  def show(duration: js.Any, easing: js.String): JQuery = ???
  def slideDown(duration: js.Any, callback: js.Any): JQuery = ???
  def slideDown(duration: js.Any): JQuery = ???
  def slideDown(): JQuery = ???
  def slideDown(duration: js.Any, easing: js.String, callback: js.Any): JQuery = ???
  def slideDown(duration: js.Any, easing: js.String): JQuery = ???
  def slideToggle(duration: js.Any, callback: js.Any): JQuery = ???
  def slideToggle(duration: js.Any): JQuery = ???
  def slideToggle(): JQuery = ???
  def slideToggle(duration: js.Any, easing: js.String, callback: js.Any): JQuery = ???
  def slideToggle(duration: js.Any, easing: js.String): JQuery = ???
  def slideUp(duration: js.Any, callback: js.Any): JQuery = ???
  def slideUp(duration: js.Any): JQuery = ???
  def slideUp(): JQuery = ???
  def slideUp(duration: js.Any, easing: js.String, callback: js.Any): JQuery = ???
  def slideUp(duration: js.Any, easing: js.String): JQuery = ???
  def stop(clearQueue: js.Boolean, jumpToEnd: js.Boolean): JQuery = ???
  def stop(clearQueue: js.Boolean): JQuery = ???
  def stop(): JQuery = ???
  def stop(queue: js.Any, clearQueue: js.Boolean, jumpToEnd: js.Boolean): JQuery = ???
  def stop(queue: js.Any, clearQueue: js.Boolean): JQuery = ???
  def stop(queue: js.Any): JQuery = ???
  def bind(eventType: js.String, eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def bind(eventType: js.String, eventData: js.Any): JQuery = ???
  def bind(eventType: js.String): JQuery = ???
  def bind(eventType: js.String, eventData: js.Any, preventBubble: js.Boolean): JQuery = ???
  def bind(eventType: js.String, preventBubble: js.Boolean): JQuery = ???
  def bind(events: js.Any*): js.Dynamic = ???
  def blur(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def blur(eventData: js.Any): JQuery = ???
  def blur(): JQuery = ???
  def blur(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def change(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def change(eventData: js.Any): JQuery = ???
  def change(): JQuery = ???
  def change(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def click(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def click(eventData: js.Any): JQuery = ???
  def click(): JQuery = ???
  def click(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def dblclick(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def dblclick(eventData: js.Any): JQuery = ???
  def dblclick(): JQuery = ???
  def dblclick(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def delegate(selector: js.Any, eventType: js.String, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def focus(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def focus(eventData: js.Any): JQuery = ???
  def focus(): JQuery = ???
  def focus(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def focusin(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def focusin(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def focusout(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def focusout(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def hover(handlerIn: js.Function1[JQueryEventObject, js.Any], handlerOut: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def hover(handlerInOut: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def keydown(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def keydown(eventData: js.Any): JQuery = ???
  def keydown(): JQuery = ???
  def keydown(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def keypress(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def keypress(eventData: js.Any): JQuery = ???
  def keypress(): JQuery = ???
  def keypress(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def keyup(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def keyup(eventData: js.Any): JQuery = ???
  def keyup(): JQuery = ???
  def keyup(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mousedown(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mousedown(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseevent(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseevent(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseenter(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseenter(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseleave(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseleave(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mousemove(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mousemove(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseout(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseout(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseover(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseover(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseup(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def mouseup(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def off(events: js.String, selector: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def off(events: js.String, selector: js.Any): JQuery = ???
  def off(events: js.String): JQuery = ???
  def off(): JQuery = ???
  def off(eventsMap: js.Any, selector: js.Any): JQuery = ???
  def off(eventsMap: js.Any): JQuery = ???
  def on(events: js.String, selector: js.Any, data: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def on(events: js.String, selector: js.Any, data: js.Any): JQuery = ???
  def on(events: js.String, selector: js.Any): JQuery = ???
  def on(events: js.String): JQuery = ???
  def on(eventsMap: js.Any, selector: js.Any, data: js.Any): JQuery = ???
  def on(eventsMap: js.Any, selector: js.Any): JQuery = ???
  def on(eventsMap: js.Any): JQuery = ???
  def one(events: js.String, selector: js.Any, data: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def one(events: js.String, selector: js.Any, data: js.Any): JQuery = ???
  def one(events: js.String, selector: js.Any): JQuery = ???
  def one(events: js.String): JQuery = ???
  def one(eventsMap: js.Any, selector: js.Any, data: js.Any): JQuery = ???
  def one(eventsMap: js.Any, selector: js.Any): JQuery = ???
  def one(eventsMap: js.Any): JQuery = ???
  def ready(handler: js.Any): JQuery = ???
  def resize(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def resize(eventData: js.Any): JQuery = ???
  def resize(): JQuery = ???
  def resize(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def scroll(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def scroll(eventData: js.Any): JQuery = ???
  def scroll(): JQuery = ???
  def scroll(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def select(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def select(eventData: js.Any): JQuery = ???
  def select(): JQuery = ???
  def select(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def submit(eventData: js.Any, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def submit(eventData: js.Any): JQuery = ???
  def submit(): JQuery = ???
  def submit(handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def trigger(eventType: js.String, extraParameters: js.Any*): JQuery = ???
  def trigger(event: JQueryEventObject): JQuery = ???
  def triggerHandler(eventType: js.String, extraParameters: js.Any*): Object = ???
  def unbind(eventType: js.String, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def unbind(eventType: js.String): JQuery = ???
  def unbind(): JQuery = ???
  def unbind(eventType: js.String, fls: js.Boolean): JQuery = ???
  def unbind(evt: js.Any): JQuery = ???
  def undelegate(): JQuery = ???
  def undelegate(selector: js.Any, eventType: js.String, handler: js.Function1[JQueryEventObject, js.Any]): JQuery = ???
  def undelegate(selector: js.Any, eventType: js.String): JQuery = ???
  def undelegate(selector: js.Any, events: js.Any): JQuery = ???
  def undelegate(namespace: js.String): JQuery = ???
  var context: Element = _
  var jquery: js.String = _
  def pushStack(elements: js.Array[js.Any]): JQuery = ???
  def pushStack(elements: js.Array[js.Any], name: js.Any, arguments: js.Any): JQuery = ???
  def after(content: js.Any*): JQuery = ???
  def after(func: js.Function1[js.Any, js.Any]): js.Dynamic = ???
  def append(content: js.Any*): JQuery = ???
  def append(func: js.Function2[js.Any, js.Any, js.Any]): js.Dynamic = ???
  def appendTo(target: js.Any): JQuery = ???
  def before(content: js.Any*): JQuery = ???
  def before(func: js.Function1[js.Any, js.Any]): js.Dynamic = ???
  def clone(withDataAndEvents: js.Boolean, deepWithDataAndEvents: js.Boolean): JQuery = ???
  def clone(withDataAndEvents: js.Boolean): JQuery = ???
  override def clone(): JQuery = ???
  def detach(selector: js.Any): JQuery = ???
  def detach(): JQuery = ???
  def empty(): JQuery = ???
  def insertAfter(target: js.Any): JQuery = ???
  def insertBefore(target: js.Any): JQuery = ???
  def prepend(content: js.Any*): JQuery = ???
  def prepend(func: js.Function2[js.Any, js.Any, js.Any]): JQuery = ???
  def prependTo(target: js.Any): JQuery = ???
  def remove(selector: js.Any): JQuery = ???
  def remove(): JQuery = ???
  def replaceAll(target: js.Any): JQuery = ???
  def replaceWith(func: js.Any): JQuery = ???
  def text(textString: js.String): JQuery = ???
  def text(): js.String = ???
  def toArray(): js.Array[js.Any] = ???
  def unwrap(): JQuery = ???
  def wrap(wrappingElement: js.Any): JQuery = ???
  def wrap(func: js.Function1[js.Any, js.Any]): JQuery = ???
  def wrapAll(wrappingElement: js.Any): JQuery = ???
  def wrapInner(wrappingElement: js.Any): JQuery = ???
  def wrapInner(func: js.Function1[js.Any, js.Any]): JQuery = ???
  def each(func: js.Function2[js.Any, Element, js.Any]): JQuery = ???
  def get(index: js.Number): js.Dynamic = ???
  def get(): js.Dynamic = ???
  def index(selectorOrElement: js.Any): js.Number = ???
  def index(): js.Number = ???
  var length: js.Number = _
  @js.annotation.JSBracketAccess
  def apply(x: js.Number): HTMLElement = ???
  @js.annotation.JSBracketAccess
  def update(x: js.Number, v: HTMLElement): Unit = ???
  def add(selector: js.String, context: js.Any): JQuery = ???
  def add(selector: js.String): JQuery = ???
  def add(elements: js.Any*): JQuery = ???
  def add(obj: JQuery): JQuery = ???
  def addBack(selector: js.Any): JQuery = ???
  def addBack(): JQuery = ???
  def children(selector: js.Any): JQuery = ???
  def children(): JQuery = ???
  def closest(selector: js.String): JQuery = ???
  def closest(selector: js.String, context: Element): JQuery = ???
  def closest(obj: JQuery): JQuery = ???
  def closest(element: js.Any): JQuery = ???
  def closest(selectors: js.Any, context: Element): js.Array[js.Any] = ???
  def contents(): JQuery = ???
  def end(): JQuery = ???
  def eq(index: js.Number): JQuery = ???
  def filter(selector: js.String): JQuery = ???
  def filter(func: js.Function1[js.Any, js.Any]): JQuery = ???
  def filter(element: js.Any): JQuery = ???
  def filter(obj: JQuery): JQuery = ???
  def find(selector: js.String): JQuery = ???
  def find(element: js.Any): JQuery = ???
  def find(obj: JQuery): JQuery = ???
  def first(): JQuery = ???
  def has(selector: js.String): JQuery = ???
  def has(contained: Element): JQuery = ???
  def is(selector: js.String): js.Boolean = ???
  def is(func: js.Function1[js.Any, js.Any]): js.Boolean = ???
  def is(element: js.Any): js.Boolean = ???
  def is(obj: JQuery): js.Boolean = ???
  def last(): JQuery = ???
  def map(callback: js.Function2[js.Any, Element, js.Any]): JQuery = ???
  def next(selector: js.String): JQuery = ???
  def next(): JQuery = ???
  def nextAll(selector: js.String): JQuery = ???
  def nextAll(): JQuery = ???
  def nextUntil(selector: js.String, filter: js.String): JQuery = ???
  def nextUntil(selector: js.String): JQuery = ???
  def nextUntil(): JQuery = ???
  def nextUntil(element: Element, filter: js.String): JQuery = ???
  def nextUntil(element: Element): JQuery = ???
  def not(selector: js.String): JQuery = ???
  def not(func: js.Function1[js.Any, js.Any]): JQuery = ???
  def not(element: js.Any): JQuery = ???
  def not(obj: JQuery): JQuery = ???
  def offsetParent(): JQuery = ???
  def parent(selector: js.String): JQuery = ???
  def parent(): JQuery = ???
  def parents(selector: js.String): JQuery = ???
  def parents(): JQuery = ???
  def parentsUntil(selector: js.String, filter: js.String): JQuery = ???
  def parentsUntil(selector: js.String): JQuery = ???
  def parentsUntil(): JQuery = ???
  def parentsUntil(element: Element, filter: js.String): JQuery = ???
  def parentsUntil(element: Element): JQuery = ???
  def prev(selector: js.String): JQuery = ???
  def prev(): JQuery = ???
  def prevAll(selector: js.String): JQuery = ???
  def prevAll(): JQuery = ???
  def prevUntil(selector: js.String, filter: js.String): JQuery = ???
  def prevUntil(selector: js.String): JQuery = ???
  def prevUntil(): JQuery = ???
  def prevUntil(element: Element, filter: js.String): JQuery = ???
  def prevUntil(element: Element): JQuery = ???
  def siblings(selector: js.String): JQuery = ???
  def siblings(): JQuery = ???
  def slice(start: js.Number, end: js.Number): JQuery = ???
  def slice(start: js.Number): JQuery = ???
}

@js.annotation.JSName("jQuery")
object JQuery extends JQueryStatic {
}
